name: Pipeline 1

trigger:
- master
- dev

pr:
  - master
  - dev

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    env
  displayName: 'Run a multi-line script'